name: test GITHUB_REF
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App Name (tests)'
        required: true
        default: tests
      env:
        description: 'Image Target Env'
        required: true
        default: 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}