name: contriner

on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:16-alpine3.16
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
          