name: contriner

on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: jianmingtu/simple-docker-nodejs-api-app
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\":\"Hello\",\"address\":\"dwded\"}'"
      - name: Get a users  
        run: curl http://localhost:3001/api/users      
          